apiVersion: v2
name: todo
description: todo
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: mongodb
    version: "13.9.4"
    repository: "https://charts.bitnami.com/bitnami"
