fqdn: todo.cisco.com
openshift: true

api:
  image: containers.cisco.com/cxinnovations/todo-api:1.0.0
server:
  image: containers.cisco.com/cxinnovations/openresty:1.21.4.1-3-bullseye-openidc

sso:
  prod: true
  client_id: null
  client_secret: null

appdynamics:
  enabled: true

  # agent
  app: todo
  node: cae

  # controller
  host: cisco1.saas.appdynamics.com
  account: cisco1
  accesskey: null

mongodb:
  # https://github.com/bitnami/charts/tree/main/bitnami/mongodb

  architecture: standalone

  image:
    registry: containers.cisco.com
    repository: cxinnovations/bitnami-mongodb
    tag: 6.0.5-debian-11-r11

  auth:
    enabled: true
    rootUser: root
    rootPassword: null

  podSecurityContext:
    fsGroup: 1012300000

  containerSecurityContext:
    runAsUser: 1012300000

  arbiter:
    podSecurityContext:
      fsGroup: 1012300000
    containerSecurityContext:
      runAsUser: 1012300000

  hidden:
    podSecurityContext:
      fsGroup: 1012300000
    containerSecurityContext:
      runAsUser: 1012300000
