apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      containers:
        - name: server
          image: {{ .Values.server.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
            - name: build
              mountPath: /www/build
              subPath: build
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 500Mi
              cpu: 200m
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-server-cm
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: build
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-server-pvc
