apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secret
data:
  MONGO_URI: {{ printf "mongodb://root:%s@%s-mongodb.%s.svc.cluster.local:27017/" .Values.mongodb.auth.rootPassword .Release.Name .Release.Namespace | b64enc}}
  SSO_CLIENT_ID: {{ .Values.sso.client_id | b64enc }}
  SSO_CLIENT_SECRET: {{ .Values.sso.client_secret | b64enc }}
  {{- if .Values.sso.prod }}
  SSO_FQDN: {{ "cloudsso.cisco.com" | b64enc }}
  {{- else }}
  SSO_FQDN: {{ "cloudsso-test.cisco.com" | b64enc }}
  {{- end }}
